// <auto-generated />
namespace NashConnects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class swapKeysFLRegEventsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(swapKeysFLRegEventsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201712280106304_swapKeysFLRegEventsTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
